# CI de Nível 01 - Disparo Manual através de clique

name: 'Execução Manual'

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v5

      # instalação do node
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando os testes e2e
        run: yarn run e2e

      # diagnóstico
      - name: Verificar relatório gerado
        if: always()
        run: |
          echo "Conteúdo da pasta playwright-report"
          ls -la playwright-report || echo "Pasta não encontrada"

      # upload do relatório
      - name: Publicar Relatório HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-html-testes
          path: playwright-report/
          retention-days: 90

      # publicar outros artefatos de relatório
      - name: Publicar relatório de cobertura (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cobertura-html
          path: reports/coverage/lcov-report/
          retention-days: 90

      - name: Publicar lcov (coverage)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cobertura-lcov
          path: reports/coverage/lcov.info
          retention-days: 90

      - name: Publicar resultados JUnit (XML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultados-xml
          path: results.xml
          retention-days: 90

      # Preparar e publicar relatório HTML como GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: reports/coverage/lcov-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        if: always()