name: Execução Manual

on:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'yarn'

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Executar Lint
        run: yarn lint

      - name: Executar Testes Unitários (Jest)
        run: yarn test

      - name: Instalar Browsers Playwright
        run: npx playwright install --with-deps

      - name: Executar Testes E2E
        run: yarn e2e

      - name: Publicar Artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-testes
          if-no-files-found: warn
          path: |
            playwright-report/
            results.xml
            reports/
            test-results/
