# CI de Nível 01 - Disparo Manual através de clique

name: 'Execução Manual'

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v5

      # instalação do node
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando os testes e2e
        run: yarn run e2e
        